apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: log-elastic
spec:
  version: 7.2.0
  volumeClaimDeletePolicy: DeleteOnScaledownAndClusterDeletion
  # disabling tls (https://www.elastic.co/guide/en/cloud-on-k8s/2.3/k8s-tls-certificates.html#k8s-disable-tls)
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        # disabling auth (https://discuss.elastic.co/t/dont-want-to-use-https-and-user-password/202332)
        xpack.security.enabled: false
        # enabling anonymous access (https://www.elastic.co/guide/en/elasticsearch/reference/7.4/anonymous-access.html)
        xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            storageClassName: standard

